@startuml
title Sleeping Teaching Assistant

start

fork
  :TA thread starts;
  while (true) is (office hours)
    if (waiting_students == 0?) then (yes)
      :TA sleeps;
      :sem_wait(student_sem);
      :TA wakes up;
    endif

    :Call next student;
    :Help student;
    :Signal help finished;
  endwhile (end)

fork again
  :Student thread starts;
  while (true) is (needs help later)
    :Program for random time;
    :Need help;
    :lock mutex;

    if (waiting_students < 3?) then (yes)
      :Take a hallway chair;
      :waiting_students++;
      :Wake/notify TA using semaphore;
      :unlock mutex;
      :Wait for TA;
      :Get help;
    else (no)
      :No chair available;
      :unlock mutex;
      :Return to programming;
    endif
  endwhile (end)

end fork

stop
@enduml